### ISSUE TITLE
Clozes not clickable in canvas 

### ISSUE THREAD

**Issue by VerAn1015** [DearVikki/obsidian-cloze-plugin#12]
In the canvas, clozes can only be toggled by using the button in the ribbon. However, when I click on the clozes in the card, it doesn't seem to work

**Comment by DearVikki** [comment]
Got it! What I can tell now is that Canvas use a different way to display content, and it may have a different structure, or not responding to normal click event. I'll look into it and find out if its possible to integrate Cloze with Canvas seamlessly when I get time.

Thank you for your patience! :D

**Comment by DearVikki** [comment]
Sad fact..looks like Canvas only works with the editing mode of the original note, while Cloze is limited to the reading mode. So unfortunately, there's no way to make it work for now. Sorry about that!

**Comment by VerAn1015** [comment]
My apologies @DearVikki , I forgot to specify. I meant clicking the clozes in canvas when read-only is checked for the entire canvas. 
I haven't dived deep into canvas yet and was actually just checking it out when I noticed how clozes aren't clickable in its read-only state, so I don't mind this issue being present at the moment. Thank you!
