### ISSUE TITLE
[FEATURE REQUEST] Live Preview as default editing mode

### ISSUE THREAD

**Issue by tzugme** [DearVikki/obsidian-cloze-plugin#19]
It would be awesome if the plugin could work in Live Preview as well, because having to switch between the modes drastically modifies the appearance of the page. 

Would this even be possible?

Thanks!

**Comment by DearVikki** [comment]
Hey @tzugme, thanks for the suggestion! 

Unfortunately, there are a few reasons why the plugin can only work in Reading mode. Like when you're in Live Preview and try to edit a line within a cloze, it's hard to tell if you're trying to edit it or toggle the cloze. Plus, there are some additional features that rely on Obsidian API, but they only work in Reading mode.

On the other side, the whole point of Cloze is to help you memorize notes, so it might be better to keep a clear distinction between notes for editing and notes for completing and reviewing.

So, for now, the plugin can only do its thing in Reading mode. Sorry about that, and thanks again for bringing it up!
