### ISSUE TITLE
different colored highlights

### ISSUE THREAD

**Issue by falood-intrivo** [DearVikki/obsidian-cloze-plugin#25]
It may not be a question for the plugin 😂, but could I ask what plugin or tool you used to have the different highlight background colors here?
Thanks a lot

<img width="197" alt="image" src="https://github.com/DearVikki/obsidian-cloze-plugin/assets/118205391/7a35f360-684d-427c-b898-0244b4b83359">

**Comment by DearVikki** [comment]
@falood-intrivo Sure, it's also a handy Obsidian plugin, [Highlightr](https://obsidian.md/plugins?id=highlightr-plugin).
