### ISSUE TITLE
option to keep clozes revealed in live preview mode 

### ISSUE THREAD

**Issue by fredjoe7** [DearVikki/obsidian-cloze-plugin#26]
I like reviewing in reading mode and when i am in live preview mode, i like all clozes to be revealed by default.

adding an option in the plugin settings to toggle having the clozes revealed in live preview mode for all notes will be nice.

thank you.

**Comment by fredjoe7** [comment]
sorry it is actually only working in reading mode..  first time when i tried it was hiding the answer in live preview mode.. now it seems to work normally

**Comment by fredjoe7** [comment]
ok the issue is real 

Inside a table, the cloze is hidden both in live preview and reading mode.

![Screenshot 2024-04-25 220136](https://github.com/DearVikki/obsidian-cloze-plugin/assets/107930196/c576d81f-8f5a-4dd0-9cc7-6376938d6d28)

**Comment by DearVikki** [comment]
Hi there! @fredjoe7 There's a ribbon fish icon on the sidebar. Try clicking it to see if it helps. It will toggle between the visible and invisible cloze states, and this state will be set as the default cloze state under the current editing mode.

![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/18145936/af798edd-1ed3-46b2-9581-fbc6d1f36b67)

**Comment by fredjoe7** [comment]
![demo](https://github.com/DearVikki/obsidian-cloze-plugin/assets/107930196/05cc4ddd-1d49-4ca8-8ad2-4b5ffdc7adae)


as i change the notes,  the default state is not executed properly inside tables.

**Comment by DearVikki** [comment]
That seems weird.. 🤔 May I ask what appearance theme you're using (so that you can change the file by selecting from the upper bar)? And would you mind emailing this markdown file to me at wanqicn@qq.com? Thanks.

**Comment by fredjoe7** [comment]
I'm using magicuser theme.
The weird color of the display is because of blue light filters..
Change file by selecting from the upper bar is enabled by Quick Explorer plugin available in community plugins.
I'll mail you the file.

Thank you.

**Comment by DearVikki** [comment]
Hi, I'm really thankful for your support! It turns out that there is a hidden bug. This only happens under a note with embedded tables, where Obsidian will call a markdown-process function even under editing mode. Anyway, I've added a workaround. Please upgrade to the latest version (v0.0.16) to see if it works for you.

By the way, the popup title for hints has also been added. Please give it a try! Thank you.

**Comment by fredjoe7** [comment]
I have tried it out,  works well ...

Thank you for this useful plugin and great support.
