### ISSUE TITLE
show full hint when fixed cloze width is on

### ISSUE THREAD

**Issue by fredjoe7** [DearVikki/obsidian-cloze-plugin#27]
the hint to pop out so that the whole text is visible. right now with fixed cloze width enabled, there hardly the hint texts visible.

**Comment by DearVikki** [comment]
@fredjoe7 Thanks for your reply. I'm so glad you found this 🐞  haha! Yes its a known issue, and I havent figured out an apporiate solution yet. So I decided to adopt another approach to tackle it.. When you hover over the hint, an HTML raw hint will pop up to show the whole text (it's kind of like a hint for a hint 😿), but it will at least solve the problem. What do you think about it? 

![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/18145936/d7446576-9fe3-47aa-99a1-7d7e8055378a)

**Comment by fredjoe7** [comment]
This will work.. just want to read the hints ..

Thank you
