### ISSUE TITLE
Highlighted, bolded and underlined doesn't add the cloze

### ISSUE THREAD

**Issue by Chykg0** [DearVikki/obsidian-cloze-plugin#3]
Hello @DearVikki , firstable thank you for your plugin witch is very simple and pretty cool.

That's note really a problem for me, but just to tell you that create a cloze from highlighted, underlined, or bolded texts does'nt work on my computer even if the settings are checked.
It seems that only the hilghlighted text under the cursor is "clozed".

I have the last update of Obsidian and i tried on a naked vault the plugin.

Bye and thank you.

**Comment by DearVikki** [comment]
Hi @Chykg0 thanks for your sweet reply. 😃 

Oh you are just being too kind to me. It is OF COURSE a problem and I defintely wont let this kind of thing happen..even on a single computer!!  

Actually, I did find something wrong related to it and I have fixed it in the latest version (0.1.2). Could you please try again when you have time and let me know the result? Thank you so much.

Have a good day!

**Comment by DearVikki** [comment]
This issue has been closed because there has been no response. Please reach out if you have or find the answers I need so that we can investigate further.
