### ISSUE TITLE
[✨ FEATURE REQUEST] Cloze option for text enclosed in brackets (Anki style)

### ISSUE THREAD

**Issue by edmund-leibert** [DearVikki/obsidian-cloze-plugin#8]
Afternoon!

First, I have been loving the plugin. Great job!

I've been primarily using obsidian with Anki. Unfortunately, Anki structures their clozes with text surrounded by either single, or double, _brackets_. It would be nice if there was an option to **auto convert** for text enclosed in brackets.

Let me know if you desire more feedback or details regarding this feature request. Look forward to hearing back from you.

**Comment by edmund-leibert** [comment]
Hey @DearVikki!

Hey @DearVikki,

Don’t worry! You’re not at all late, Lord knows I’ve been much later in my responses in the past 😅. Hope all is well with you!

My mistake, I originally meant to say I would like an option to apply a cloze style on text enclosed in **curly brackets**, _not_ normal brackets. 

I've opened a new pull request that incorporates this feature already, allowing users to choose between converting text enclosed in single brackets. You can check it out here: [link to pull request].

Thanks again for all the work you did!

**Comment by edmund-leibert** [comment]
> @edmund-leibert Hi Edmund! I hope I'm not too late to catch your message haha.
> 
> In the latest release (version 0.1.9), I've added a new feature that automatically converts text enclosed in single brackets (since double brackets are used for linking page in Obsidian). ![image](https://private-user-images.githubusercontent.com/18145936/288348459-c3e97c60-50f8-4c8c-8592-0b20803fb89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDM2MTAsIm5iZiI6MTcwMjIwMzMxMCwicGF0aCI6Ii8xODE0NTkzNi8yODgzNDg0NTktYzNlOTdjNjAtNTBmOC00YzhjLTg1OTItMGIyMDgwM2ZiODllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEwMTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTk3YmM3Yzk5NGNhNDA3ZGY4YzM5N2U5NDVkNWJjNmVjODQ4YjlhZGU1YjcyNzNlZWJhZTYzNDFhZTA1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1FCvgUr4qDljHLAXrXWqpnTfvaZDw_uWC5OtnK9Va-4)
> 
> Give it a try and I hope you find it useful! :D

Hi @DearVikki,

Don’t worry! You’re not at all late, Lord knows I’ve been much later in my responses in the past 😅. Hope all is well with you!

My mistake, I originally meant to say I would like an option to apply a cloze style on text enclosed in **curly brackets**, _not_ normal brackets. 

I've opened a new pull request that incorporates this feature already, allowing users to choose between converting text enclosed in single brackets. You can check it out here: [link to pull request].

Thanks again for all the work you did!

**Comment by DearVikki** [comment]
Hi @edmund-leibert,

Thanks for your concern. There was something that happened in my family, but thankfully everything has been resolved now, and I'm back!

Oh I was too careless to double check the bracket with you! But You are such a great guy that you've already taken care of the request yourself haha!! I'm sooo touched 😃. I've already merged it with some teeny-tiny adjustments, and you can find it in the latest release (version 0.1.10).

![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/18145936/0e2b54a6-b9ac-44eb-b9f6-48b28b1748cc)

Wish it will be  helpful for you this time!

**Comment by edmund-leibert** [comment]
@DearVikki !

I’m relieved to hear that everything has been resolved with your family. Family matters are always important, and I’m glad you’re back! Hope you had a wonderful Christmas.

I’m pleased to know that my contribution was helpful. It was nice to collaborate and make your project better. The adjustments you made and the new release (version 0.1.10) is great! 😄 

Thanks again for your hard work and for being open about collaboration, especially with the delays in my responses. I look forward to more of your work to come!

P.S. Hope you have an awesome New Years! 🎊

**Comment by edmund-leibert** [comment]
> Hi @edmund-leibert,
> 
> Thanks for your concern. There was something that happened in my family, but thankfully everything has been resolved now, and I'm back!
> 
> Oh I was too careless to double check the bracket with you! But You are such a great guy that you even took care of the request yourself haha!! I'm sooo touched 😃. I've already merged it with some teeny-tiny adjustments, and you can find it in the latest release (version [0.1.10](https://github.com/DearVikki/obsidian-cloze-plugin/releases/tag/0.1.10) ).
> 
> ![image](https://private-user-images.githubusercontent.com/18145936/290761516-0e2b54a6-b9ac-44eb-b9f6-48b28b1748cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM4MDEzMDksIm5iZiI6MTcwMzgwMTAwOSwicGF0aCI6Ii8xODE0NTkzNi8yOTA3NjE1MTYtMGUyYjU0YTYtYjlhYy00NGViLWI5ZjYtNDhiMjhiMTc0OGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDIyMDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MjM0MDIxYzRlY2M3M2FkYzE4NmYyYTFhY2FkYmZkZDc0MDI4NDE1OWRkNjRmNjQzODVkNWQ5NDNjY2EwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scluIU71bZD1tySd2pPngLnBGW_z4sBnNgjhJFvD56o)
> 
> Wish it will be helpful for you this time!

@DearVikki !

I’m relieved to hear that everything has been resolved with your family. Family matters are always important, and I’m glad you’re back! Hope you had a wonderful Christmas.

I’m pleased to know that my contribution was helpful. It was nice to collaborate and make your project better. The adjustments you made and the new release (version 0.1.10) is great! 😄 

Thanks again for your hard work and for being open about collaboration, especially with the delays in my responses. I look forward to more of your work to come!

P.S. Hope you have an awesome New Years! 🎊
